{% set name = "StrEnum" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b15ccff9eb0e22e77b8f874366ea752754280adc9144e6e388705d14cc350e7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python >=3.6
    - pytest-runner
    - pip
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - strenum

about:
  home: https://github.com/irgeek/StrEnum
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python Enum that inherits from str.
  description: |
    A Python Enum that inherits from str.

extra:
  recipe-maintainers:
    - timkpaine
